name: Deploy Flutter Web to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0' # Use the Flutter version you need

      - name: Install dependencies
        run: cd admin && flutter pub get

      - name: Build Flutter web
        run: cd admin && flutter build web

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-dir: ./admin/build/web
          project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: ${{ secrets.VERCEL_ALIAS_DOMAINS }}
