name: Deploy Flutter Web to Vercel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Production – ecommerce-app-cross-platform-admin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'

      - name: Install dependencies
        run: cd admin && flutter pub get

      - name: Build Flutter web
        run: cd admin && flutter build web

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Debug environment variables
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}"
          echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID }}"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel deploy --prebuilt --token $VERCEL_TOKEN --prod --confirm --project $VERCEL_PROJECT_ID

      - name: Clear Flutter Cache
        run: cd admin && flutter pub cache repair
